---
# This part will deploy and setup Kubernetes on all devices.
- hosts: all
  become: true
  roles:
    - common

# This part will initiate Kubernetes on the master node.
- hosts: master
  become: true
  roles:
    - masters

# This part will join the nodes in the cluster.
- hosts: nodes
  become: true
  roles:
    - nodes

#Install the shared storage on rpi-k8s-node-2
- hosts:
    - rpi-k8s-node-2
  become: true
  roles:
    - apps/nfs-server

# This part will install and set up the applications/services.
- hosts: master
  become: true
  roles:
    - k8s/namespaces
    - apps/dynamic-dns
    - apps/wireguard
