- name: Download Linkerd script
  get_url:
    url: https://run.linkerd.io/install
    dest: /tmp/linkerd-install.sh
    mode: 0777

- name: Install Linkerd cli
  shell: "sh /tmp/linkerd-install.sh"

- name: Create linkerd symlink
  file:
    src: $HOME/.linkerd2/bin/linkerd
    dest: /usr/local/bin/linkerd
    mode: 0777
    owner: root
    group: root
    state: link

- name: Put linkerd template
  template:
    src: linkerd.yml.j2
    dest: /tmp/linkerd.yml
    mode: 0777

- name: Linkerd apply
  shell: "kubectl apply -f /tmp/linkerd.yml"

- name: Upgrade the control plane
  shell: "linkerd upgrade | kubectl apply --prune -l linkerd.io/control-plane-ns=linkerd -f -"
