---
- name: Add autocompeltion source
  shell:
    cmd: |
        kubectl completion bash > ~/.kube/completion.bash.inc
        printf "
        source '$HOME/.kube/completion.bash.inc'
        " >> $HOME/.bash_profile
        source $HOME/.bash_profile
  ignore_errors: true

- name: Check if Kubernetes has already been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Restart service docker, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Restart service kubelet, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: Initialize Kubernetes master
  command: >
    kubeadm init --apiserver-advertise-address="{{ IpAddress.k8s_master }}" --pod-network-cidr={{ K8s.podSubnet }} --upload-certs
  register: kubeadmin_init
  when: not kubernetes_init_stat.stat.exists

- name: Change own
  shell: mkdir -p $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config
  when: not kubernetes_init_stat.stat.exists

#- name: Create .kube directory
#  file:
#    path: $HOME/.kube
#    state: directory
#    owner: root
#    group: root
#    mode: 0775

#- name: copy default cluster configuration
#  shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#  args:
#    chdir: $HOME
#    creates: $HOME/.kube/config

#- name: change config mode
#  file:
#    path: $HOME/.kube/config
#    state: file
#    owner: root
#    group: root
#    mode: 0660

#- name: Change own
#  file:
#    path: $HOME/.kube/config 
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#    mode: 0644

- name: Convert flannel Yaml template
  become: true
  template:
    src: kube-flannel.yml.j2
    dest: /tmp/kube-flannel.yml
    mode: 0777

#- name: Delete old flannel
#  shell: kubectl delete -f /tmp/kube-flannel.yml

#sed -i 's#10.244.0.0/16#10.1.0.0/16#' kube-flannel.yml
#sed -i 's/vxlan/host-gw/' kube-flannel.yml
#https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
#https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
- name: Apply flannel
  shell: kubectl apply -f /tmp/kube-flannel.yml

- name: Convert Metric Yaml template
  become: true
  template:
    src: metric-components.yaml.j2
    dest: /tmp/metric-components.yaml
    mode: 0777

- name: apply Metric Yaml template
  shell: kubectl apply -f /tmp/metric-components.yaml