- name: Create kubernetes join token
  become: yes
  ansible.builtin.shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Display k8s join command
  ansible.builtin.debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Create file kubernetes_join_command
  shell: echo '{{ kubernetes_join_command.stdout_lines[0] }}' > /tmp/kubernetes_join_command

- name: Copy join command to local file
  fetch:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    flat: yes